### PR TITLE
Add support for extra labels and annotations

### PR DESCRIPTION
**Pull request by vbehar**
add the following Helm values:
- `labels` for the statefulset
- `annotations` for the statefulset
- `podLabels` for the pods
- `podAnnotations` for the pods

### CODE REVIEW

**Comment by vbehar** [comment]
ping @spkesan - thanks!

**Comment by vbehar** [comment]
hi @spkesan, is this repository still maintained? thanks

**Comment by rbotzer** [comment]
@vbehar yes, it's still maintained. SP will get around to it in about a week.

**Comment by vbehar** [comment]
Ok great thanks

**Comment by vbehar** [comment]
ping @spkesan - thanks!

**Review by spkesan — APPROVED** [review]

**Comment by spkesan** [comment]
Thanks @vbehar for the time and effort.
The changes look good.

**Pull request merged**
